package view;

import dao.AlumnoDAO;
import entity.Alumno;

/**
 *
 * @author ERIC GUSTAVO CORONEL CASTILLO
 * @email  gcoronelc@gmail.com
 */
public class EditFormView extends javax.swing.JDialog {

	// Variables locales
	private AlumnoDAO dao = new AlumnoDAO(); // Componente DAO
	private Integer id; // Código del alumno

	// Método para inyectar el código del alumno
	public void setId(Integer id) throws Exception {
		this.id = id;
		initForm();
	}

	/** Creates new form EditView */
	public EditFormView(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      txtApellido = new javax.swing.JTextField();
      txtNombre = new javax.swing.JTextField();
      txtNota = new javax.swing.JTextField();
      btnCerrar = new javax.swing.JButton();
      btnGrabar = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("FALTA");
      setBackground(java.awt.SystemColor.inactiveCaptionText);
      setResizable(false);

      jLabel1.setText("Apellido");

      jLabel2.setText("Nombre");

      jLabel3.setText("Nota");

      btnCerrar.setText("Cerrar");
      btnCerrar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCerrarActionPerformed(evt);
         }
      });

      btnGrabar.setText("Grabar");
      btnGrabar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnGrabarActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(106, Short.MAX_VALUE))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(201, Short.MAX_VALUE)
            .addComponent(btnGrabar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnCerrar)
            .addGap(26, 26, 26))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(19, 19, 19)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(19, 19, 19)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(34, 34, 34)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnGrabar)
               .addComponent(btnCerrar))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

	 private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
		 this.setVisible(false);
	 }//GEN-LAST:event_btnCerrarActionPerformed

	 private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
		 try {
			 Alumno alu = new Alumno();
			 alu.setApellido(this.txtApellido.getText());
			 alu.setNombre(this.txtNombre.getText());
			 alu.setNota(Integer.parseInt(this.txtNota.getText()));
			 if (this.id == null) {
				 dao.create(alu);
			 } else {
				 alu.setId(id);
				 dao.update(alu);
			 }
			 util.Util.showMessage(this, "Proceso ejecutado correctamente.");
			 if( this.id == null ){
				 cleanForm();
			 }
		 } catch (Exception e) {
			 util.Util.showError(this, e.getMessage());
		 }
	 }//GEN-LAST:event_btnGrabarActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				EditFormView dialog = new EditFormView(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {

					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnCerrar;
   private javax.swing.JButton btnGrabar;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JTextField txtApellido;
   private javax.swing.JTextField txtNombre;
   private javax.swing.JTextField txtNota;
   // End of variables declaration//GEN-END:variables

	private void initForm() throws Exception {
		if (this.id == null) {
			this.setTitle("NUEVO ALUMNO");
			cleanForm();
		} else {
			this.setTitle("EDITAR ALUMNO " + this.id);
			loadAlumno();
		}
	}

	private void cleanForm() {
		this.txtApellido.setText("");
		this.txtNombre.setText("");
		this.txtNota.setText("");
		this.txtApellido.grabFocus();
	}

	private void loadAlumno() throws Exception {
		Alumno alu = dao.read(this.id);
		this.txtApellido.setText(alu.getApellido());
		this.txtNombre.setText(alu.getNombre());
		this.txtNota.setText(String.valueOf(alu.getNota()));
		this.txtApellido.grabFocus();
	}
}
